name: search_users
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  go_router: ^7.0.1
  json_annotation: ^4.8.1
  retry: ^3.1.2
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter

  freezed: ^2.3.4
  json_serializable: ^6.7.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

scripts:
  build: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch --delete-conflicting-outputs
